### ISSUE TITLE
Add styles through H6 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#36]
These still need a little hierarchy. Right now they are just appearing as normal text

**Comment by johnvf** [comment]
Done.

**Comment by marishaf** [comment]
I tried this the doc 3_Design and H5 and H6 are still appearing as normal text

**Comment by johnvf** [comment]
Styles were added, but they are never applied - it looks like the h5 and h6 headings are never exported in Word. 

They show up in the page as 'p' elements. 

We are using a 3rd party tool to generate HTML (actually, 'Markdown') from .docx: https://www.npmjs.com/package/mammoth

I'd rather not debug this issue with mammoth if it can be worked around instead. Can H1-H4, lists, tables, or some other graphical tool be used to communicate this information?

**Comment by johnvf** [comment]
Another option would be for you guys to learn Markdown, the text could then be modified by you before being input:

https://en.wikipedia.org/wiki/Markdown
